### ISSUE TITLE
Wrong length prefix in packetC3I

### ISSUE THREAD

**Issue by BRA1L0R** [arduino/ucPack-mpy#5]
Hi,

How can this message have a length prefix of 5 though it contains 7 bytes of data? It's not used anywhere in the alvik library so i think it just got overlooked.

https://github.com/arduino/ucPack-mpy/blob/cf677269a932a44bfb6f301786472044d925c01d/ucPack/ucPack.py#L248C1-L252C65

**Comment by eigen-value** [comment]
Thanks for helping @BRA1L0R it's been fixed in https://github.com/arduino/ucPack-mpy/commit/d171dd089c89e0179169385f6c947e3859bdd587
will be available in the next release of ucPack-mpy
